version: "2"
services:
    php:
        build: ./docker/php
        volumes: 
            - ./app:/app
    web:
        image: "nginx:1.13.8-alpine"
        volumes: 
            - ./app:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "83:80"
        links:
            - "php"    